name: NokiaAntiCheat
version: 1.0.0
main: com.nokia.anticheat.NokiaAntiCheat
api-version: 1.21
author: Nokia Security Team
description: Advanced anti-cheat system with admin protection
website: https://nokia.com
